import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/layouts/header";
import Footer from "@/components/layouts/footer";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata = {
    title: "Marketing Stark",
    description: "Generated by create Marketing Stark",
    icons: {
        icon: [
            {
                rel: "icon",
                type: "image/png",
                sizes: "96x96",
                url: "/favicon-96x96.png",
            },
            { rel: "icon", type: "image/svg+xml", url: "/favicon.svg" },
        ],
        apple: "/apple-touch-icon.png",
        shortcut: "/favicon.ico",
    },
    manifest: "/site.webmanifest",
    appleWebApp: {
        title: "Marketing Stark",
    },
};
export default function RootLayout({ children }) {
    return (
        <html lang='en'>
            <body className={`${geistSans.variable} ${geistMono.variable}`}>
                <Header />
                <div className='container'>{children}</div>
                <Footer />
            </body>
        </html>
    );
}
